name: lubao_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  lucide_icons: ^0.257.0
  skeletonizer: ^3.0.0
  flutter_animate: ^4.5.2
  socket_io_client: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Variable.ttf
          weight: 400
        - asset: assets/fonts/Onest-Variable.ttf
          weight: 500
        - asset: assets/fonts/Onest-Variable.ttf
          weight: 600
        - asset: assets/fonts/Onest-Variable.ttf
          weight: 700
        - asset: assets/fonts/Onest-Variable.ttf
          weight: 800
